site_name: Robert Moerman
site_description: "Robert Moerman's homepage"
site_author: Robert Moerman
site_url: https://mrmrob003.github.io/
repo_name: mrmrob003.github.io
repo_url: https://github.com/mrmrob003/mrmrob003.github.io

nav:
  - Home: index.md

theme:
  name: readthedocs
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch between light and dark mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.expand
    - content.code.highlight
    - content.code.tabs
    - content.code.toggle
    - content.code.view
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggestions
    - search.highlight
    - toc.integrate
    - toc.follow
    - toc.sticky
    - toc.deep_linking

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
      base_path: [!relative $config_dir]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      allow_errors: true
      include_source: true
      ignore_h1_titles: true